### ISSUE TITLE
Fix for google Search

### ISSUE THREAD

**Issue by tenebris0011** [phazyy/Startpage#1]
Not sure if you are still using this startpage anymore, but I came across it and quite like it.
Thought I might submit a fix for you, for the google search issue. 
Here is the code I modified to make google search work.
`<div class="twelve columns panel panel-blue" id="search">`
`<form method="get" action="https://www.google.com/search">`
`<input class="u-full-width" type="Text" name="q"`
`placeholder="Google"\>`
The code above makes google search work for me on my forked version of your site.

**Comment by ahstn** [comment]
Nice work.
Do you want to submit a pull request so I can take a look at it and merge it?

**Comment by tenebris0011** [comment]
Sorry didn't realize how to do that. Went ahead and made a pull request.
